### PR TITLE
Update the combine icon

### PR DESCRIPTION
**Pull request by harleo**
Update the combine icon to correctly represent a union/combination

### CODE REVIEW

**Review by yochannah — COMMENTED** [review]
@harleo this looks great! I tweaked the viewbox slightly and fixed a minor syntax error (don't worry about that, I appreciate you can't see the compiled results!). One small question though: it seems to be a bit darker now, any idea why? I tried changing the fill to rgba(0,0,0,0.3) but it didn't seem to make a difference.

**Comment by yochannah** [comment]
image
 darker icon. If fixing it isn't obvious, just let me know and we'll merge anyway because this icon is still good :) Thank you so much!!!!

**Comment by yochannah** [comment]
@harleo P.S. - if you need another hacktoberfest PR, we opened another ticket for a similar icon. IF you don't, no worries :) https://github.com/intermine/bluegenes/issues/159

**Comment by harleo** [comment]
@yochannah I see what you mean. Try using `rgb(212, 212, 212)` or `#d4d4d4` as the fill color, see if that works out. It's a happy little accident though, and it makes sense. If you combine two things, their color will merge/combine and the result is _one_ color, if you know what I mean 😄

Regarding the other issue, I'll take a look and see what I can do!

**Comment by yochannah** [comment]
hah, it was actually a bad local css style. your code was great!

**Pull request merged**
