### PR TITLE
fix: discrepancies in lock file after setting up project

### LINKED ISSUE #695: Discrepancy in package-lock.json after setting up project
**Current Behaviour**
After doing `npm install`, there are several discrepancy in the package-lock.json file

**Actual Behaviour**
No discrepancy in package versions should be present

**OS**
Ubuntu

### PR DESCRIPTION
**Pull request by meenal06**
This text can be deleted when you are ready to make the pull request: 
fixes #695 

For each PR, please add the following, if appropriate: 

- After setting up project through `npm install` there are various changes in lockfile done.
-#965
- Run `npm install` after checking out the branch

### CODE REVIEW

**Comment by meenal06** [comment]
Hi @uosl , looks like the failure is not due to my PR but cypress complaining

**Comment by heralden** [comment]
> Hi @uosl , looks like the failure is not due to my PR but cypress complaining

You're right. Some of the current Cypress tests can be unstable (hoping we can improve this), so some will fail at random.

**Comment by heralden** [comment]
What version of node.js and npm are you using? I'm using v14.16.0 and 6.4.11, and when running `npm install` on your branch it will revert to the old lock file. It looks like this package lock file is of a newer version. I will have to investigate whether they are backwards compatible and they recommend upgrading.

**Comment by meenal06** [comment]
I am on node v15.7 and nom v7.4.3, also the updates are backwards compatible. I have verified building the project with the new changes.

**Comment by heralden** [comment]
A problem is that when running `npm install` with an older version, it will rewrite the lockfile into the older format. I assume that most people will be using v14 which is on Active LTS (odd-numbered releases are considered unstable by Node). I would rather wait until node v16 enters Active LTS and becomes more widespread, before updating the lockfile.

Thank you for letting us know about this. I'll be closing the PR.

**Pull request closed without merging**
