### PR TITLE
Update README.md : Make more beautify 

### PR DESCRIPTION
**Pull request by localanu**
README.md : change the formatting
The format of the header isn't good, look below

screenshot_2017-10-03_21-32-08

It's no beautiful,and I changed it

### CODE REVIEW

**Comment by yochannah** [comment]
@localanu this PR came through quite quickly - did you manage to complete the entire readme and BlueGenes setup? How did it go? 

If you have any other content to add to this PR, that would be great! Just changing a couple of headers probably isn't meaningful enough to accept as it is.

I'll leave this PR open until tomorrow in case you would like to add anything. If we don't hear back, I'll close this with the invalid label.

**Comment by localanu** [comment]
@yochannah can't I change the formating? and I changed the pull comment

**Comment by localanu** [comment]
I was doing change a formating

**Comment by localanu** [comment]
@yochannah I was explain in my pull comment right now

**Comment by yochannah** [comment]
Hi @localanu - unfortunately I can't accept the pull request as-is since it's a bit too trivial,  but I'll look forward to your next one. If you have any questions about BlueGenes then definitely drop me a line. Thanks for your interest in BlueGenes!

**Pull request closed without merging**
