### PR TITLE
Fix indenting

### PR DESCRIPTION
**Pull request by allentiak**
### Please describe your PR:

Just a quick indentation fix from parinfer[0] while I start working on my GSoC 2019 application ;-)
This PR only affects code structure.

[0] Parinfer: https://shaunlebron.github.io/parinfer/

### Review checklist: 

 Before merging, confirm the following tasks have been executed

- [ ] review a _minified_ build (e.g. `lein prod`, _not_ `lein figwheel`). 

Checked the following pages load results successfully and allow you to proceed to the results or report page:

- [ ] Upload page resolves IDs as expected
- [ ] Templates execute and show results
- [ ] Templates allow you to select lists AND type in identifiers
- [ ] Search (dropdown preview version)
- [ ] Search (full results page)
- [ ] Report page loads, including homologues and tools
- [ ] Region search
- [ ] Login and logout works for more than one user (use test user demo@intermine.org pw demo if needed)

This is not an exhaustive list - if you spot something else strange please bring it up!

### CODE REVIEW

**Comment by sehgalvibhor** [comment]
@allentiak : `lein cljfmt check` is failing now (Travis CI). I think the indentation is correct; cljfmt checks for any formatting issues :) Two files have formatting issues now, you can refer to the Travis log for more details.

**Comment by allentiak** [comment]
Thanks for your quick reply.

Hmmm... This is interesting... I will check it.
Could you please copy the error message into this thread?

(I followed the suggestion from Atom's `parinfer` plugin  - I didn't
imagine there would be any difference between that and `cljfmt`...)

**Comment by sehgalvibhor** [comment]
Um, not really sure why would that happen. Here is the error log for reference : 

```
src/cljs/bluegenes/components/ui/results_preview.cljs has incorrect formatting
--- a/home/travis/build/intermine/bluegenes/src/cljs/bluegenes/components/ui/results_preview.cljs
+++ b/home/travis/build/intermine/bluegenes/src/cljs/bluegenes/components/ui/results_preview.cljs
@@ -31,13 +31,13 @@
        [:tbody
         (if
          (< (:iTotalRecords query-results) 1)
-         [:tr
-          [:td {:col-span (count (:columnHeaders query-results))}
-           [:h4 "Query returned no results"]]]
-         (doall (map-indexed
-                 (fn [idx r]
-                   ^{:key idx} [table-row r])
-                 (:results query-results))))
+          [:tr
+           [:td {:col-span (count (:columnHeaders query-results))}
+            [:h4 "Query returned no results"]]]
+          (doall (map-indexed
+                  (fn [idx r]
+                    ^{:key idx} [table-row r])
+                  (:results query-results))))
         (if (and (not hide-count?) (> (:iTotalRecords query-results) 5))
           [:tr
            [:td
src/cljs/bluegenes/components/idresolver/events_inplace.cljs has incorrect formatting
--- a/home/travis/build/intermine/bluegenes/src/cljs/bluegenes/components/idresolver/events_inplace.cljs
+++ b/home/travis/build/intermine/bluegenes/src/cljs/bluegenes/components/idresolver/events_inplace.cljs
@@ -71,7 +71,7 @@
                                                 (cond->
                                                  {:identifiers (if (seq ids) ids [ids])
                                                   :type object-type}
-                                                 (not= organism :any) (assoc :extra organism)))]
+                                                  (not= organism :any) (assoc :extra organism)))]
      (go (dispatch [:handle-id (<! job)])))))
 
 (reg-event-fx
@@ -301,7 +301,7 @@
            ;sets example to any type configured as a fallback
           (assoc-in db example-keys any-example-type)
            ;if there's a default type, set the example to it instead.
-          use-default? (assoc-in example-keys object-type-default))
+           use-default? (assoc-in example-keys object-type-default))
      :text (if use-default? example-text-default any-example-text)}))
 
 (reg-event-fx
2 file(s) formatted incorrectly
```

**Comment by allentiak** [comment]
Thanks again for your quick reply.

This is indeed weird... From a diff, the difference pattern is, in all
cases, a single leading white space...

I will re-check things with `parinfer` tomorrow and get back to you.

**Comment by allentiak** [comment]
My guess is that this is a bug from either `atom-parinfer` or `lein-cljfmt`...

**Comment by sehgalvibhor** [comment]
> My guess is that this is a bug from either `atom-parinfer` or `lein-cljfmt`...

Yes, can be!

> Thanks again for your quick reply. This is indeed weird... From a diff, the difference pattern is, in all cases, a single leading white space... I will re-check things with `parinfer` tomorrow and get back to you.

Sure :)

**Comment by allentiak** [comment]
While I figure out whether `atom-parinfer` or `lein-cljfmt` is wrong, I fixed the indenting of the offending files so `lein-checkfmt` won't complain anymore. All tests pass now :-)

**Comment by allentiak** [comment]
Wait. Don't merge it yet. I think I've catched a few usage errors.

**Comment by allentiak** [comment]
I can finally say it: Ready! :-)

**Comment by allentiak** [comment]
BTW: I chose to avoid squashing these commits to allow an eventual research on the indenting algorithm differences between `lein-cljfmt` and `atom-parinfer` I discovered while working on this PR.

**Comment by sehgalvibhor** [comment]
> I can finally say it: Ready! :-)

@allentiak : I am just a contributor (no privileges), I think someone from the Intermine team will review it and follow up with you :)

**Comment by yochannah** [comment]
okay, I'm back from vacation - y'all have totally cracked me up in this thread. Thanks @sehgalvibhor for your help reviewing this!

**Pull request merged**
