### PR TITLE
Sort by rank - ascending order

### LINKED ISSUE #129: Sort templates by rank
Courtesy of @julie-sullivan :

"I just added rank to the template JSON"

```
"name":"AllGene_Chromosome",
         "comment":"",
         "tags":[  
            "im:aspect:Genes",
            "im:public"
         ],
         "rank":"2",
```

### PR DESCRIPTION
**Pull request by sehgalvibhor**
### Please describe your PR:
Closes #129 

### Review checklist: 

 Before merging, confirm the following tasks have been executed

- [ ] review a _minified_ build (e.g. `lein prod`, _not_ `lein figwheel`). 

Checked the following pages load results successfully and allow you to proceed to the results or report page:

- [ ] Upload page resolves IDs as expected
- [ ] Templates execute and show results
- [ ] Templates allow you to select lists AND type in identifiers
- [ ] Search (dropdown preview version)
- [ ] Search (full results page)
- [ ] Report page loads, including homologues and tools
- [ ] Region search
- [ ] Login and logout works for more than one user (use test user demo@intermine.org pw demo if needed)

This is not an exhaustive list - if you spot something else strange please bring it up!

### CODE REVIEW

**Comment by yochannah** [comment]
@sehgalvibhor I'm really sorry but can't actually get this to work. I see this order, for HumanMine (tested with Fly too). 

image

But on HumanMine the order is 

image

I wasn't sure *which* was the correct order - it's conceivable that HumanMine is wrong. This script also matches humanmine's ordering, though https://codepen.io/yochannah/pen/ebGZRp?editors=0011#0

**Comment by sehgalvibhor** [comment]
Okay, must be something wrong I did. But, a part of the result is sorted and a part is not. 
https://jsoneditoronline.org/?id=599c446840ed40dc9fa49d1bc9c94a64

Maybe this output will help (Flymine)! If you see, a lot of elements are sorted on the rank. Interestingly, when I change rank to name, it does sort everything alphabetically.

**Comment by yochannah** [comment]
hmm, at a guess, I think could be because the rank is (somewhat incorrectly) returned as a string. 

```clojure
(.parseInt js/window "12")
```

that's the basic syntax (using js methods) to parse a string to an int.

**Comment by yochannah** [comment]
I've logged the issue here: https://github.com/intermine/intermine/issues/1976

**Comment by sehgalvibhor** [comment]
I also think that's the case, thank you so much :)

**Comment by yochannah** [comment]
Okay! As a side note, we should probably just parse the strings to int for now rather than wait for InterMine.

**Comment by sehgalvibhor** [comment]
Okay, let me try typecasting to see if it works correctly or not.

**Comment by sehgalvibhor** [comment]
Um, I am directly applying type casting in the comp function ``` (comp #(.parseInt js/window (:rank second))) ```. Is this wrong way of doing it, as the result is not sorted?

**Comment by yochannah** [comment]
Whoops, I just hopped onto this PR to see what the status was and realised it was waiting on my response. So sorry!!

**Comment by yochannah** [comment]
The ticket to return ints as ints ( https://github.com/intermine/intermine/issues/1976 ) has been closed as a won't/can't fix, so we definitely need to work around the issue. I suspect the reason the comp above wasn't working is that we had a lot of NaNs - there are two types of rank, an int presenting as a string, e.g. `"12"` and also real strings, for templates with no rank yet - `"unranked"`. I'll merge your PR but I've added a little if function to turn unranked templates into rank 99999 as a hack to make them sort to the end.

**Pull request merged**
