### PR TITLE
Tool API version 1.0

### PR DESCRIPTION
**Pull request by yochannah**
### Please describe your PR:

This is a very simple implementation of the tool api. It currently allows the following: 
- any tools installed in the [tools folder](https://github.com/yochannah/bluegenes/blob/tool-api-2018/tools/docs/tools.md#published-tools) will automatically be loaded on the relevant pages (e.g. a gene tool will load on gene pages, etc.). 
- browse tools in the tool store. This currently only lists what is installed and points to documentation, but longer term it will allow you to install, uninstall, and tweak config. To view this, go to the developer page (top right navbar > cog > developer) and then visit the tool app store. 

### Review checklist: 

 Before merging, confirm the following tasks have been executed

#### Tool API specific testing: 

Once you've pulled the PR to your local machine:

1. Set up a couple of tools. 
    - [x] Follow the [Published Tools Guidelines](https://github.com/yochannah/bluegenes/blob/tool-api-2018/tools/docs/tools.md) to install the [two current published tools](https://www.npmjs.com/search?q=keywords:bluegenes-intermine-tool). 
     - [ ] Check documentation is clear enough. 
2. Once the tools are installed, you'll need to check the following:
     - [x] review a _minified_ build (e.g. `lein cljsbuild once min` + `lein run`, _not_ `lein figwheel`). 
          - [x] Can you see the complete tool listing under (top right navbar > cog > developer)?
          - [x] Visit the report page for a protein. Do the tools you'd expect to show up appear?
          - [x] Visit the report page for a gene. Do the tools you'd expect to show up appear?
     - [x] review a BlueGenes launched via InterMine as a Gradle target. You'll need to pass a variable to bluegenes in order for it to know where to look for the BlueGenes tools folder. See the "launching Bluegenes via a JAR" section of the [docs](https://github.com/yochannah/bluegenes/blob/tool-api-2018/tools/docs/tools.md#when-launching-bluegenes-via-a-jar)
          - [x] Can you see the complete tool listing under (top right navbar > cog > developer)?
          - [x] Visit the report page for a protein. Do the tools you'd expect to show up appear?
          - [x] Visit the report page for a gene. Do the tools you'd expect to show up appear?
3. Other: 
    - [x] Does the [Tool API](https://github.com/yochannah/bluegenes/blob/tool-api-2018/tools/docs/tool-api.md) and [Tool API tutorial](https://github.com/yochannah/bluegenes/blob/tool-api-2018/tools/docs/tool-api-tutorial.md) make sense?  
#### General checks: 

Confirm the following pages load results successfully and allow you to proceed to the results or report page:

- [x] ID resolver + results preview
- [x] Templates execute and show results
- [x] Templates allow you to select lists AND type in identifiers
- [ ] Search (dropdown preview version)
- [ ] Search (full results page)
- [x] Report page loads, including homologues and tools
- [x] Region search
- [x] Login and logout works for more than one user (use test user demo@intermine.org pw demo if needed)

This is not an exhaustive list - if you spot something else strange please bring it up!

### CODE REVIEW

**Comment by julie-sullivan** [comment]
https://github.com/yochannah/bluegenes/blob/tool-api-2018/src/clj/bluegenes/ws/tools.md#published-tools

Link to "tool API guidelines" is broken

**Comment by julie-sullivan** [comment]
`Tool API tutorial ` linked above isn't there.

**Comment by julie-sullivan** [comment]
I did this:

* checked out yochannah/bluegenes branch `tool-api-2018`
* installed the two tools
* `lein cljsbuild once min + lein run` successfully

I get this on firefox and chrome:

bluegenes

I did a CTRL+refresh.

**Comment by yochannah** [comment]
hmm, that error I thought shouldn't happen on a minified build, but maybe I'm wrong. Try running `lein less once` and tell me if the visuals improve?

**Comment by julie-sullivan** [comment]
```
julie ~/git/bluegenes $ lein less once
Compiling {less} css:
less/im-tables-overrides.less => resources/public/css/im-tables-overrides.css
FileError: 'variables.less' wasn't found in /local-data/git/bluegenes/less/overrides.less on line 2, column 1:
1 @import "variables";
2 @import "../resources/public/vendor/bootstrap/less/variables";
3 
```

**Comment by yochannah** [comment]
pull&try again?

**Comment by julie-sullivan** [comment]
that worked! I had to do `bower install` twice.

**Comment by yochannah** [comment]
I've updated the tutorial link (and the other docs links, as I put them in a silly place rather than a logical place, originally.

The tutorial is _not_ complete yet.

**Comment by julie-sullivan** [comment]
```
Uncaught Error: Invalid arity: 3
    at L.a [as call] (app.js?v=0.9.4-SNAPSHOT:399)
    at app.js?v=0.9.4-SNAPSHOT:380
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
glyphicons-halflings-regular.woff2:1 Failed to load resource: the server responded with a status of 500 (Response map is nil)
glyphicons-halflings-regular.woff:1 Failed to load resource: the server responded with a status of 500 (Response map is nil)
glyphicons-halflings-regular.ttf:1 Failed to load resource: the server responded with a status of 500 (Response map is nil)
2app.js?v=0.9.4-SNAPSHOT:1476 Uncaught TypeError: Cannot read property 'main' of undefined
    at app.js?v=0.9.4-SNAPSHOT:1476
    at qqa (app.js?v=0.9.4-SNAPSHOT:1477)
    at nwa (app.js?v=0.9.4-SNAPSHOT:2831)
    at HTMLScriptElement.<anonymous> (app.js?v=0.9.4-SNAPSHOT:2832)
app.js?v=0.9.4-SNAPSHOT:1243 Uncaught Error: Invalid arity: 3
    at L.a [as call] (app.js?v=0.9.4-SNAPSHOT:399)
    at app.js?v=0.9.4-SNAPSHOT:380
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
    at Function.Yh.Y (app.js?v=0.9.4-SNAPSHOT:380)
2app.js?v=0.9.4-SNAPSHOT:1476 Uncaught TypeError: Cannot read property 'main' of undefined
    at app.js?v=0.9.4-SNAPSHOT:1476
    at qqa (app.js?v=0.9.4-SNAPSHOT:1477)
    at nwa (app.js?v=0.9.4-SNAPSHOT:2831)
    at HTMLScriptElement.<anonymous> (app.js?v=0.9.4-SNAPSHOT:2832)
```

**Comment by yochannah** [comment]
where/when does this happen?

**Comment by julie-sullivan** [comment]
lola

**Comment by yochannah** [comment]
Okay, this is totally a bug. Why did it work for me before? no-one knows! I probably should have `lein clean`ed at some point and didn't. 

https://github.com/intermine/bluegenes/issues/279

I'll comment on this issue when I think it's fixed.

**Comment by yochannah** [comment]
@julie-sullivan Okay, I think the refactor to fix this is complete, I hope.

To test: 

1. Pull the new changes to bluegenes. Make sure to close down any running bluegenes process if they were still open, then re-launch them. 
2. in `bluegenes/tools` run `npm update` to pull down the changes in the tools packages

**Comment by julie-sullivan** [comment]
I still see the tools in the app store (yay!) but I don't see them on the report page. Before the headings were there but the tool was empty. Now I don't even see the headings.

I saw a few errors in the console, including:
```
app.js?v=0.9.4-SNAPSHOT:567 Uncaught TypeError: re-find must match against a string.
    at rk (app.js?v=0.9.4-SNAPSHOT:567)
    at RQ (app.js?v=0.9.4-SNAPSHOT:967)
    at XY (app.js?v=0.9.4-SNAPSHOT:1290)
    at b (app.js?v=0.9.4-SNAPSHOT:1292)
    at a (app.js?v=0.9.4-SNAPSHOT:1292)
    at vl.f.D (app.js?v=0.9.4-SNAPSHOT:616)
    at gZ (app.js?v=0.9.4-SNAPSHOT:1306)
    at app.js?v=0.9.4-SNAPSHOT:2811
    at Function.b [as j] (app.js?v=0.9.4-SNAPSHOT:2809)
    at sQ (app.js?v=0.9.4-SNAPSHOT:941)
```

**Comment by yochannah** [comment]
I thiiiinnnnnnnnkkkkkkk that 0.9.8-SNAPSHOT will have the correct goodies in it. 
You'll also need to set 
`environment("bluegenes-tool-path", props.getProperty("bluegenes.toolLocation"))` and ensure that in your properties file (e.g. `~/intermine/flymine.properties)` bluegenes.toolLocation is configured to the place your tools are installed. For me the correct path is `/intermine/tools/node_modules`

**Comment by yochannah** [comment]
@julie-sullivan do you need anything else from me for this PR?

**Comment by julie-sullivan** [comment]
no, I don't need anything else, everything looks great!

**Comment by yochannah** [comment]
@julie-sullivan okay, this branch is back up to speed with dev. There may well be regressions. Please test & finalise checkboxes!

**Comment by yochannah** [comment]
Also, let me know if you need another jar built or if you're happy to test locally.

**Comment by yochannah** [comment]
@julie-sullivan okay - could I get you to pull the most recent changes and see what happens? and/or try 0.9.9 which I just pushed to Clojars.

Probably do a `lein clean` before anything else.

**Comment by julie-sullivan** [comment]
On the [debug console](http://localhost:5000/#/debug/main) I see
```
Current mine:
FlyMine at http://http://localhost:8080/flymine
```
When I click on it, it goes a different wrong URL
```
http//localhost:8080/flymine
```

**Comment by julie-sullivan** [comment]
**List Upload**

* defaults to protein. Can we default to the first item on the list instead? (Genes in this case)
* I can't save a list because I keep getting this error. This is true if I am logged in or not.

debug

**Comment by julie-sullivan** [comment]
@yochannah I can log in and save a list now! I will keep testing the other items.

**Comment by yochannah** [comment]
We have confirmation TOOL API 1.0 IS GO!

💯 🥇 🎉 🍾

**Pull request merged**
