### PR TITLE
SVG: Fix icons for difference and subtract set operations #562

### PR DESCRIPTION
**Pull request by Saffafatima12**
Tried fixing the design for icons.

### NEW DESIGN

**1. when two or more in list are selected (dark background)**
svg_click

**2. when less than two selected in list (light background)**
svg_nclick

### OLD DESIGN

**1. when two or more in list are selected (dark background)**
svg_click_old

**2. when less than two selected in list (light background)**
svg_nclick_old

### CODE REVIEW

**Comment by heralden** [comment]
The *Combine* icon looks perfect now!

A few things to do first:
1. Change the `:viewbox` property directly below `svg` to be `:viewBox` instead (the "B" needs to be uppercase).
2. Run `lein format` in the bluegenes directory to fix indentation of the new svg source.
3. For *:svg#icon-venn-combine*, change the line below it to have the same viewBox as the other icons: `{:viewBox "-5 0 160 100"}` Without this the scaling will be different. You can also delete the `"\n{:fill-rule \"evenodd\",\n:fill \"none\",\n:stroke-width \"1\",:stroke \"none\"}\n"` line below it, as that was left there before as a mistake and doesn't do anything.

Finally, the new icons look like your screenshot for the dark background, but for the light background they're slightly different:
2020-11-18-170708_1515x120_scrot
You can see that the center part is dark for *Difference* and *Subtract*, when it should be light. It would be great if you're able to fix this.

Thanks again for your help! :+1:

**Comment by Saffafatima12** [comment]
@uosl thank you for your comments! I will need to look into why the the shading in icons turns out to be different from what I see in my browser. I will try my best to correct all the mistakes as soon as possible :)

**Comment by Saffafatima12** [comment]
1. I changed the `:viewbox` to `:viewBox` for all the four icons.
2. Ran lein format in the bluegenes directory to fix indentation of the new svg source.
3. For :svg#icon-venn-combine, I changed the line below it to have the same viewBox as the other icons: {:viewBox "-5 0 160 100"} 
4. Deleted the "\n{:fill-rule \"evenodd\",\n:fill \"none\",\n:stroke-width \"1\",:stroke \"none\"}\n" line.
5. Tried to fix the shading for difference and subtract (Please let me know if it works)

Please do let me know if there are more errors and I will be happy to correct them :) Thank you!

**Review by heralden — APPROVED** [review]

**Comment by heralden** [comment]
Thank you for the quick corrections!

Everything looks great now. Thank you so much, this has been a big help :100:

**Comment by Saffafatima12** [comment]
Thank you so much @uosl ! I would have never been able to do this without your help! :)

**Pull request merged**
