### PR TITLE
feat: reorganise and fix login specs

### PR DESCRIPTION
**Pull request by meenal06**
For each PR, please add the following, if appropriate: 

- reorganised the login spec
- refers #700
- checkout on local and run with cypress

### CODE REVIEW

**Comment by meenal06** [comment]
Hi @uosl , This PR fixes and reorganises the login specs. If this looks good to you, I will make a successive PR for registration specs too.

**Comment by heralden** [comment]
The diff looks great, this is much cleaner :+1:. However, it fails with `TypeError: cy.openLoginDialogue`. I assume this is because this function is defined in the folders that used to be in gitignore until #697. Can you please add it to this PR before I merge?

**Comment by meenal06** [comment]
Hi @uosl , I have updated the PR please have a look!

**Review by heralden — APPROVED** [review]

**Comment by heralden** [comment]
Judging by the artifacts on CircleCI, the single login-logout test that failed seems to be a flake. We'll improve on this later.

Thanks for your contribution!

**Pull request merged**
