### PR TITLE
Migrate from bower to npm

### PR DESCRIPTION
**Pull request by heralden**
### Please describe your PR:

This is for fixing https://github.com/intermine/bluegenes/issues/283. I followed getting-started.md both before and after making my changes, making sure stuff looked the same. I also tested a `lein prod` production build.

I wasn't able to run the tests with `lein doo phantom test once` however, as I got the error below with a fresh repo.
`clojure.lang.ExceptionInfo: failed compiling file:<REDACTED>/bluegenes/test/cljs/re_frame_boiler/core_test.cljs {:file #object[java.io.File 0x5af5d76f ":<REDACTED>/bluegenes/test/cljs/re_frame_boiler/core_test.cljs"]}`

In addition to cleaning up `package.json` as I saw fit when merging in `bower.json`, (also creating an `.npmignore` to mimic the `ignore` field in `bower.json`) I also made changes to wherever I found `bower` to be mentioned, replacing it with `npm`.

### CODE REVIEW

**Comment by heralden** [comment]
Thanks Travis! Looks like I didn't manage to test this properly since I hadn't cleared out the directories in `resouces/public/` after migrating to npm. Working on a fix for this now.

**Comment by heralden** [comment]
@yochannah I'm not sure what is the best approach to fix this. I see now that `.bowerrc` is used to install the bower packages into `resources/public/vendor`, which some files of are imported to less source files or to the head of index.html (which is generated in `bluegenes.index`). 

`package.json` doesn't seem to have any functionality to cherry-pick packages to be moved to a different directory, so to mimic the bower behaviour, a build step has to be added to do this. A different approach would be to edit the less source files so they include stuff from the `node_modules` folder instead, and to use CDN or dist files checked into the repo, in index.html where `resources/public/vendor` is used. I see that CDN is already used for gridlex and jquery, so I'm guessing that those bower packages aren't in use.

May be some stuff I missed. What do you think?

**Comment by yochannah** [comment]
hmmm, I think I'll have to pull this to have a look and a think - thanks so much for making a start! :)

**Comment by yochannah** [comment]
In the process of investigating I accidentally fixed it :laughing: - editing the files to point to node_modules instead of the vendor folder. 

@uosl Thank you so much for this PR! :heart: I'll look at your other one next

**Comment by heralden** [comment]
Thanks for merging!

But I noticed that some scripts in `src/clj/bluegenes/index.clj` link to files in the vendor folder, provided by bower. I think these should be replaced by CDN, similarly to how gridlex and jquery are? Since you won't be able to link to node_modules there, which is outside the web root.

**Comment by yochannah** [comment]
Whoops - I totally missed that! The CDN approach sounds good.

**Pull request merged**
