### PR TITLE
Change questionmark icon

### LINKED ISSUE #162: SVG+hiccup: Replace homepage questionmark icon with more sans-serif style questionmark
**Picking this issue up:**
1. Read through and make sure you understand the task (it's ok to ask questions if needed)
2. Leave a comment on the issue saying you intend to work in it

**specs:**

See the blue questionmark here: [http://bluegenes.apps.intermine.org/](http://bluegenes.apps.intermine.org/).

image

It doesn't seem to really fit with the other two icons - we need to replace with an icon that looks a bit more in keeping with the theme.

The icon is located here: https://github.com/intermine/bluegenes/blob/dev/src/cljs/bluegenes/components/icons.cljs#L332 this is in hiccup, rather than html, but can be translated to html easily http://htmltohiccup.herokuapp.com/

see https://github.com/intermine/bluegenes/issues/157 for a related ticket discussing converting html to hiccup and back

### PR DESCRIPTION
**Pull request by artiemq**
Fix #162 

Now it looks like this

### CODE REVIEW

**Review by yochannah — APPROVED** [review]
Brilliant Job!

**Comment by yochannah** [comment]
Nicely done and thank you! How did you get on with the project setup - was it straightforward?

Email me your address to yo@intermine.org if you'd like an InterMine sticker as thanks!

**Comment by artiemq** [comment]
Setup was very easy. I could not run the tests but looks like they're absent, if it is so  https://github.com/intermine/bluegenes/blob/dev/README.md#run-tests is unnecessary :)

**Comment by yochannah** [comment]
good to hear. And *cough* you're right about the tests - that's something we need to fix :(

**Pull request merged**
