### PR TITLE
My data: make mobile friendly (er)

### PR DESCRIPTION
**Pull request by yochannah**
### Please describe your PR:
This page now squishes to smaller screens more effectively, addressing #184. I've also migrated the folder structure as follows:
- migrate all mymine components into the same folder
- migrate the lists subs file to mymine folder (these subs were still used)
- delete the rest of the lists folder. 

### Review checklist: 

 Before merging, confirm the following tasks have been executed

- [x] review a _minified_ build (e.g. `lein cljsbuild min once` + `lein run`, _not_ `lein figwheel`). 

Checked the following pages load results successfully and allow you to proceed to the results or report page:

- [x] ID resolver + results preview
- [x] Templates execute and show results
- [ ] Templates allow you to select lists AND type in identifiers
- [x] Search (dropdown preview version)
- [x] Search (full results page)
- [x] Report page loads, including homologues and tools
- [x] Region search

This is not an exhaustive list - if you spot something else strange please bring it up!

### CODE REVIEW

**Comment by yochannah** [comment]
I've added a few more commits, that generally do the following: 
- logon box: 
  - has a register button 
  - isn't overshadowed by nav bar
  - tells you *where* you're logging in to
- subtract in the list page now automatically adds smallest list to the subtract side.
- some other minor aesthetic tweaks.

**Comment by joshkh** [comment]
Everything looks good except for one CSS issue. `less/components/lists.less` was deleted which contains the styling for list constraint dropdowns, specifically the `dropdown-mixed-content` class:

https://github.com/intermine/bluegenes/pull/202/files#diff-8280409f61041d431e668904625f313dL172

image

**Comment by yochannah** [comment]
how'bout now? 
image

**Comment by joshkh** [comment]
Approved!

**Pull request merged**
